#!/bin/bash

# ./Connect4 ".ryyrry,.rryry.,..y.r..,..y....,.......,......." red M 1

# ./Connect4 "..y.r..,..y.r..,.......,.......,.......,......." yellow M 1

# ./Connect4 "..yyrrr,..ryryr,....y..,.......,.......,......." red M 1

./Connect4 "..yyrrr,rrryryr,....y..,.......,.......,......." red M 1